import random
import math
from datetime import datetime, timedelta

HOME_ADVANTAGE = 1.25

# Realistic team ratings based on 2024/25 season performance
# attack/defense are relative to league average (1.0)
LEAGUE_TEAMS = {
    "PL": [
        {"name": "Manchester City",    "attack": 1.90, "defense": 0.62},
        {"name": "Arsenal",            "attack": 1.72, "defense": 0.65},
        {"name": "Liverpool",          "attack": 1.78, "defense": 0.68},
        {"name": "Aston Villa",        "attack": 1.52, "defense": 0.74},
        {"name": "Chelsea",            "attack": 1.48, "defense": 0.79},
        {"name": "Tottenham",          "attack": 1.55, "defense": 0.83},
        {"name": "Newcastle United",   "attack": 1.42, "defense": 0.80},
        {"name": "Manchester United",  "attack": 1.30, "defense": 0.92},
        {"name": "West Ham United",    "attack": 1.28, "defense": 0.90},
        {"name": "Brighton",           "attack": 1.35, "defense": 0.84},
        {"name": "Wolves",             "attack": 1.18, "defense": 0.96},
        {"name": "Fulham",             "attack": 1.24, "defense": 0.89},
        {"name": "Bournemouth",        "attack": 1.22, "defense": 0.94},
        {"name": "Crystal Palace",     "attack": 1.12, "defense": 0.96},
        {"name": "Brentford",          "attack": 1.26, "defense": 0.91},
        {"name": "Everton",            "attack": 1.08, "defense": 1.02},
        {"name": "Nottingham Forest",  "attack": 1.15, "defense": 0.94},
        {"name": "Ipswich Town",       "attack": 1.00, "defense": 1.06},
        {"name": "Leicester City",     "attack": 1.04, "defense": 1.08},
        {"name": "Southampton",        "attack": 0.92, "defense": 1.18},
    ],
    "PD": [
        {"name": "Real Madrid",        "attack": 2.05, "defense": 0.58},
        {"name": "Barcelona",          "attack": 1.88, "defense": 0.62},
        {"name": "Atletico Madrid",    "attack": 1.56, "defense": 0.63},
        {"name": "Girona",             "attack": 1.48, "defense": 0.73},
        {"name": "Athletic Club",      "attack": 1.42, "defense": 0.78},
        {"name": "Real Sociedad",      "attack": 1.36, "defense": 0.82},
        {"name": "Real Betis",         "attack": 1.30, "defense": 0.84},
        {"name": "Villarreal",         "attack": 1.32, "defense": 0.85},
        {"name": "Valencia",           "attack": 1.18, "defense": 0.92},
        {"name": "Las Palmas",         "attack": 1.14, "defense": 0.96},
        {"name": "Getafe",             "attack": 1.06, "defense": 0.90},
        {"name": "Osasuna",            "attack": 1.10, "defense": 0.92},
        {"name": "Alaves",             "attack": 0.98, "defense": 1.02},
        {"name": "Rayo Vallecano",     "attack": 1.16, "defense": 0.98},
        {"name": "Sevilla",            "attack": 1.20, "defense": 0.92},
        {"name": "Mallorca",           "attack": 0.98, "defense": 0.94},
        {"name": "Celta Vigo",         "attack": 1.14, "defense": 1.02},
        {"name": "Leganes",            "attack": 0.94, "defense": 1.06},
        {"name": "Espanyol",           "attack": 0.98, "defense": 1.08},
        {"name": "Valladolid",         "attack": 0.88, "defense": 1.14},
    ],
    "CL": [
        {"name": "Real Madrid",            "attack": 2.10, "defense": 0.58},
        {"name": "Manchester City",        "attack": 1.95, "defense": 0.60},
        {"name": "Bayern Munich",          "attack": 1.90, "defense": 0.62},
        {"name": "Arsenal",                "attack": 1.72, "defense": 0.65},
        {"name": "Barcelona",              "attack": 1.85, "defense": 0.63},
        {"name": "Paris Saint-Germain",    "attack": 1.78, "defense": 0.68},
        {"name": "Atletico Madrid",        "attack": 1.55, "defense": 0.65},
        {"name": "Liverpool",              "attack": 1.80, "defense": 0.67},
        {"name": "Bayer Leverkusen",       "attack": 1.68, "defense": 0.70},
        {"name": "Inter Milan",            "attack": 1.62, "defense": 0.68},
        {"name": "Borussia Dortmund",      "attack": 1.55, "defense": 0.75},
        {"name": "PSV Eindhoven",          "attack": 1.50, "defense": 0.78},
        {"name": "Real Sociedad",          "attack": 1.35, "defense": 0.82},
        {"name": "Benfica",                "attack": 1.42, "defense": 0.80},
        {"name": "Celtic",                 "attack": 1.20, "defense": 0.92},
        {"name": "Porto",                  "attack": 1.38, "defense": 0.82},
    ],
    "EL": [
        {"name": "Atalanta",               "attack": 1.72, "defense": 0.68},
        {"name": "Bayer Leverkusen",       "attack": 1.68, "defense": 0.70},
        {"name": "Roma",                   "attack": 1.48, "defense": 0.78},
        {"name": "Ajax",                   "attack": 1.52, "defense": 0.80},
        {"name": "Porto",                  "attack": 1.40, "defense": 0.82},
        {"name": "Marseille",              "attack": 1.38, "defense": 0.84},
        {"name": "Villarreal",             "attack": 1.32, "defense": 0.85},
        {"name": "Sporting CP",            "attack": 1.36, "defense": 0.80},
        {"name": "Slavia Prague",          "attack": 1.22, "defense": 0.90},
        {"name": "Rangers",                "attack": 1.18, "defense": 0.94},
        {"name": "West Ham United",        "attack": 1.28, "defense": 0.90},
        {"name": "Fiorentina",             "attack": 1.30, "defense": 0.88},
        {"name": "Sevilla",                "attack": 1.20, "defense": 0.92},
        {"name": "Real Betis",             "attack": 1.28, "defense": 0.86},
        {"name": "Braga",                  "attack": 1.24, "defense": 0.88},
        {"name": "Liverpool",              "attack": 1.78, "defense": 0.68},
    ],
    "BL1": [
        {"name": "Bayern Munich",          "attack": 1.98, "defense": 0.60},
        {"name": "Bayer Leverkusen",       "attack": 1.75, "defense": 0.65},
        {"name": "Borussia Dortmund",      "attack": 1.62, "defense": 0.72},
        {"name": "RB Leipzig",             "attack": 1.58, "defense": 0.70},
        {"name": "Union Berlin",           "attack": 1.30, "defense": 0.85},
        {"name": "SC Freiburg",            "attack": 1.28, "defense": 0.84},
        {"name": "Eintracht Frankfurt",    "attack": 1.40, "defense": 0.80},
        {"name": "Wolfsburg",              "attack": 1.22, "defense": 0.90},
        {"name": "Borussia Monchengladbach","attack": 1.25, "defense": 0.88},
        {"name": "Mainz 05",               "attack": 1.18, "defense": 0.92},
        {"name": "Werder Bremen",          "attack": 1.20, "defense": 0.94},
        {"name": "Hoffenheim",             "attack": 1.24, "defense": 0.91},
        {"name": "FC Koln",                "attack": 1.10, "defense": 0.98},
        {"name": "FC Augsburg",            "attack": 1.08, "defense": 1.00},
        {"name": "Bochum",                 "attack": 1.00, "defense": 1.06},
        {"name": "Heidenheim",             "attack": 1.04, "defense": 1.04},
        {"name": "Darmstadt",              "attack": 0.92, "defense": 1.14},
        {"name": "VfL Bochum",             "attack": 0.96, "defense": 1.10},
    ],
    "SA": [
        {"name": "Inter Milan",            "attack": 1.85, "defense": 0.62},
        {"name": "AC Milan",               "attack": 1.70, "defense": 0.67},
        {"name": "Juventus",               "attack": 1.55, "defense": 0.68},
        {"name": "Napoli",                 "attack": 1.72, "defense": 0.68},
        {"name": "Atalanta",               "attack": 1.68, "defense": 0.65},
        {"name": "Roma",                   "attack": 1.48, "defense": 0.78},
        {"name": "Lazio",                  "attack": 1.45, "defense": 0.80},
        {"name": "Fiorentina",             "attack": 1.38, "defense": 0.82},
        {"name": "Bologna",                "attack": 1.32, "defense": 0.85},
        {"name": "Torino",                 "attack": 1.22, "defense": 0.90},
        {"name": "Monza",                  "attack": 1.18, "defense": 0.92},
        {"name": "Genoa",                  "attack": 1.12, "defense": 0.96},
        {"name": "Lecce",                  "attack": 1.08, "defense": 1.00},
        {"name": "Udinese",                "attack": 1.10, "defense": 0.98},
        {"name": "Sassuolo",               "attack": 1.15, "defense": 0.95},
        {"name": "Hellas Verona",          "attack": 1.05, "defense": 1.02},
        {"name": "Frosinone",              "attack": 1.00, "defense": 1.06},
        {"name": "Empoli",                 "attack": 1.02, "defense": 1.04},
        {"name": "Cagliari",               "attack": 0.98, "defense": 1.08},
        {"name": "Salernitana",            "attack": 0.90, "defense": 1.14},
    ],
    "FL1": [
        {"name": "Paris Saint-Germain",    "attack": 2.05, "defense": 0.58},
        {"name": "Monaco",                 "attack": 1.65, "defense": 0.70},
        {"name": "Brest",                  "attack": 1.52, "defense": 0.72},
        {"name": "Lille",                  "attack": 1.48, "defense": 0.74},
        {"name": "Lyon",                   "attack": 1.42, "defense": 0.80},
        {"name": "Marseille",              "attack": 1.38, "defense": 0.82},
        {"name": "Nice",                   "attack": 1.35, "defense": 0.82},
        {"name": "Rennes",                 "attack": 1.28, "defense": 0.86},
        {"name": "Lens",                   "attack": 1.30, "defense": 0.84},
        {"name": "Toulouse",               "attack": 1.18, "defense": 0.92},
        {"name": "Reims",                  "attack": 1.15, "defense": 0.94},
        {"name": "Montpellier",            "attack": 1.10, "defense": 0.98},
        {"name": "Strasbourg",             "attack": 1.12, "defense": 0.96},
        {"name": "Nantes",                 "attack": 1.08, "defense": 1.00},
        {"name": "Le Havre",               "attack": 1.05, "defense": 1.02},
        {"name": "Metz",                   "attack": 0.98, "defense": 1.06},
        {"name": "Clermont",               "attack": 0.92, "defense": 1.10},
        {"name": "Lorient",                "attack": 0.88, "defense": 1.14},
    ],
    "CO1": [
        {"name": "Atletico Nacional",      "attack": 1.65, "defense": 0.70},
        {"name": "Millonarios",            "attack": 1.58, "defense": 0.72},
        {"name": "America de Cali",        "attack": 1.52, "defense": 0.75},
        {"name": "Junior",                 "attack": 1.45, "defense": 0.78},
        {"name": "Deportivo Cali",         "attack": 1.35, "defense": 0.85},
        {"name": "Once Caldas",            "attack": 1.20, "defense": 0.92},
        {"name": "Independiente Medellin", "attack": 1.38, "defense": 0.82},
        {"name": "Deportes Tolima",        "attack": 1.30, "defense": 0.88},
        {"name": "Santa Fe",               "attack": 1.25, "defense": 0.90},
        {"name": "Envigado",               "attack": 1.05, "defense": 1.02},
        {"name": "La Equidad",             "attack": 1.08, "defense": 0.98},
        {"name": "Aguilas Doradas",        "attack": 1.10, "defense": 0.96},
        {"name": "Deportivo Pasto",        "attack": 1.02, "defense": 1.04},
        {"name": "Deportivo Pereira",      "attack": 1.12, "defense": 0.95},
        {"name": "Alianza Petrolera",      "attack": 0.98, "defense": 1.06},
        {"name": "Union Magdalena",        "attack": 0.95, "defense": 1.08},
        {"name": "Jaguares",               "attack": 0.90, "defense": 1.10},
        {"name": "Boyaca Chico",           "attack": 0.88, "defense": 1.12},
        {"name": "Fortaleza",              "attack": 0.92, "defense": 1.10},
        {"name": "Deportivo Rionegro",     "attack": 0.95, "defense": 1.08},
    ],
    "ERL": [
        {"name": "Ajax",                   "attack": 1.85, "defense": 0.62},
        {"name": "PSV Eindhoven",          "attack": 1.78, "defense": 0.65},
        {"name": "Feyenoord",              "attack": 1.65, "defense": 0.68},
        {"name": "AZ Alkmaar",             "attack": 1.48, "defense": 0.75},
        {"name": "FC Twente",              "attack": 1.38, "defense": 0.80},
        {"name": "Utrecht",                "attack": 1.28, "defense": 0.86},
        {"name": "Sparta Rotterdam",       "attack": 1.20, "defense": 0.92},
        {"name": "NEC Nijmegen",           "attack": 1.15, "defense": 0.94},
        {"name": "Heerenveen",             "attack": 1.12, "defense": 0.96},
        {"name": "Groningen",              "attack": 1.05, "defense": 1.02},
        {"name": "Go Ahead Eagles",        "attack": 1.08, "defense": 1.00},
        {"name": "Almere City",            "attack": 0.98, "defense": 1.06},
        {"name": "PEC Zwolle",             "attack": 0.95, "defense": 1.08},
        {"name": "Waalwijk",               "attack": 0.92, "defense": 1.10},
        {"name": "Heracles",               "attack": 0.90, "defense": 1.12},
        {"name": "Fortuna Sittard",        "attack": 0.88, "defense": 1.14},
        {"name": "Excelsior",              "attack": 0.85, "defense": 1.16},
        {"name": "Volendam",               "attack": 0.82, "defense": 1.18},
    ],
    "PRL": [
        {"name": "Benfica",                "attack": 1.88, "defense": 0.60},
        {"name": "Sporting CP",            "attack": 1.82, "defense": 0.62},
        {"name": "Porto",                  "attack": 1.78, "defense": 0.64},
        {"name": "Braga",                  "attack": 1.42, "defense": 0.78},
        {"name": "Vitoria Guimaraes",      "attack": 1.28, "defense": 0.86},
        {"name": "Famalicao",              "attack": 1.15, "defense": 0.94},
        {"name": "Estoril",                "attack": 1.10, "defense": 0.96},
        {"name": "Casa Pia",               "attack": 1.08, "defense": 0.98},
        {"name": "Moreirense",             "attack": 1.04, "defense": 1.02},
        {"name": "Rio Ave",                "attack": 1.05, "defense": 1.00},
        {"name": "Farense",                "attack": 0.98, "defense": 1.04},
        {"name": "Arouca",                 "attack": 0.96, "defense": 1.05},
        {"name": "Gil Vicente",            "attack": 0.94, "defense": 1.06},
        {"name": "Estrela Amadora",        "attack": 0.90, "defense": 1.10},
        {"name": "Boavista",               "attack": 1.12, "defense": 0.96},
        {"name": "Vizela",                 "attack": 0.88, "defense": 1.12},
        {"name": "Chaves",                 "attack": 0.86, "defense": 1.14},
        {"name": "Nacional",               "attack": 0.84, "defense": 1.16},
    ],
    "SUP": [
        {"name": "Galatasaray",            "attack": 1.85, "defense": 0.62},
        {"name": "Fenerbahce",             "attack": 1.80, "defense": 0.63},
        {"name": "Besiktas",               "attack": 1.58, "defense": 0.72},
        {"name": "Trabzonspor",            "attack": 1.42, "defense": 0.78},
        {"name": "Basaksehir",             "attack": 1.35, "defense": 0.82},
        {"name": "Sivasspor",              "attack": 1.20, "defense": 0.90},
        {"name": "Alanyaspor",             "attack": 1.18, "defense": 0.92},
        {"name": "Antalyaspor",            "attack": 1.12, "defense": 0.96},
        {"name": "Kasimpasa",              "attack": 1.10, "defense": 0.98},
        {"name": "Gaziantep",              "attack": 1.05, "defense": 1.02},
        {"name": "Konyaspor",              "attack": 1.02, "defense": 1.04},
        {"name": "Kayserispor",            "attack": 0.98, "defense": 1.06},
        {"name": "Adana Demirspor",        "attack": 1.15, "defense": 0.95},
        {"name": "Hatayspor",              "attack": 0.96, "defense": 1.05},
        {"name": "Rizespor",               "attack": 0.92, "defense": 1.08},
        {"name": "Samsunspor",             "attack": 0.90, "defense": 1.10},
        {"name": "Pendikspor",             "attack": 0.88, "defense": 1.12},
        {"name": "Istanbulspor",           "attack": 0.85, "defense": 1.15},
    ],
    "LIB": [
        {"name": "Flamengo",               "attack": 1.88, "defense": 0.62},
        {"name": "River Plate",            "attack": 1.82, "defense": 0.64},
        {"name": "Palmeiras",              "attack": 1.78, "defense": 0.65},
        {"name": "Atletico Mineiro",       "attack": 1.68, "defense": 0.68},
        {"name": "Boca Juniors",           "attack": 1.60, "defense": 0.70},
        {"name": "Fluminense",             "attack": 1.55, "defense": 0.72},
        {"name": "Nacional",               "attack": 1.42, "defense": 0.78},
        {"name": "Penarol",                "attack": 1.40, "defense": 0.80},
        {"name": "Colo Colo",              "attack": 1.35, "defense": 0.83},
        {"name": "LDU Quito",              "attack": 1.30, "defense": 0.86},
        {"name": "San Lorenzo",            "attack": 1.25, "defense": 0.90},
        {"name": "Gremio",                 "attack": 1.22, "defense": 0.91},
        {"name": "Sao Paulo",              "attack": 1.28, "defense": 0.88},
        {"name": "Estudiantes",            "attack": 1.20, "defense": 0.92},
        {"name": "Independiente del Valle","attack": 1.38, "defense": 0.82},
        {"name": "Barcelona SC",           "attack": 1.18, "defense": 0.94},
    ],
    "SUD": [
        {"name": "Corinthians",            "attack": 1.55, "defense": 0.73},
        {"name": "Santos",                 "attack": 1.48, "defense": 0.76},
        {"name": "Racing Club",            "attack": 1.52, "defense": 0.74},
        {"name": "Independiente",          "attack": 1.45, "defense": 0.78},
        {"name": "Athletico Paranaense",   "attack": 1.42, "defense": 0.80},
        {"name": "Olimpia",                "attack": 1.35, "defense": 0.84},
        {"name": "Cerro Porteno",          "attack": 1.30, "defense": 0.86},
        {"name": "Bolivar",                "attack": 1.28, "defense": 0.88},
        {"name": "Sporting Cristal",       "attack": 1.22, "defense": 0.91},
        {"name": "Alianza Lima",           "attack": 1.20, "defense": 0.92},
        {"name": "Libertad",               "attack": 1.18, "defense": 0.93},
        {"name": "Huracan",                "attack": 1.15, "defense": 0.95},
        {"name": "Defensa y Justicia",     "attack": 1.32, "defense": 0.85},
        {"name": "Goias",                  "attack": 1.12, "defense": 0.97},
        {"name": "Fortaleza",              "attack": 1.25, "defense": 0.90},
        {"name": "Atletico Nacional",      "attack": 1.38, "defense": 0.83},
    ],
    "MLS": [
        {"name": "Inter Miami",            "attack": 1.75, "defense": 0.68},
        {"name": "Columbus Crew",          "attack": 1.55, "defense": 0.72},
        {"name": "LAFC",                   "attack": 1.65, "defense": 0.70},
        {"name": "New England Revolution", "attack": 1.40, "defense": 0.78},
        {"name": "Seattle Sounders",       "attack": 1.48, "defense": 0.74},
        {"name": "Philadelphia Union",     "attack": 1.42, "defense": 0.76},
        {"name": "NY City FC",             "attack": 1.38, "defense": 0.80},
        {"name": "Atlanta United",         "attack": 1.35, "defense": 0.82},
        {"name": "Portland Timbers",       "attack": 1.32, "defense": 0.84},
        {"name": "LA Galaxy",              "attack": 1.45, "defense": 0.77},
        {"name": "Orlando City",           "attack": 1.28, "defense": 0.86},
        {"name": "Chicago Fire",           "attack": 1.20, "defense": 0.92},
        {"name": "FC Dallas",              "attack": 1.22, "defense": 0.90},
        {"name": "Nashville SC",           "attack": 1.30, "defense": 0.85},
        {"name": "Austin FC",              "attack": 1.25, "defense": 0.88},
        {"name": "St Louis City",          "attack": 1.15, "defense": 0.95},
        {"name": "San Jose Earthquakes",   "attack": 1.10, "defense": 0.98},
        {"name": "Real Salt Lake",         "attack": 1.18, "defense": 0.93},
    ],
    "LMX": [
        {"name": "Club America",           "attack": 1.82, "defense": 0.63},
        {"name": "Cruz Azul",              "attack": 1.65, "defense": 0.68},
        {"name": "Chivas Guadalajara",     "attack": 1.58, "defense": 0.72},
        {"name": "Tigres UANL",            "attack": 1.72, "defense": 0.66},
        {"name": "Monterrey",              "attack": 1.68, "defense": 0.67},
        {"name": "Pumas UNAM",             "attack": 1.42, "defense": 0.78},
        {"name": "Leon",                   "attack": 1.38, "defense": 0.80},
        {"name": "Pachuca",                "attack": 1.45, "defense": 0.76},
        {"name": "Toluca",                 "attack": 1.35, "defense": 0.83},
        {"name": "Santos Laguna",          "attack": 1.28, "defense": 0.87},
        {"name": "Atletico San Luis",      "attack": 1.20, "defense": 0.92},
        {"name": "Tijuana",                "attack": 1.18, "defense": 0.94},
        {"name": "Puebla",                 "attack": 1.15, "defense": 0.96},
        {"name": "Necaxa",                 "attack": 1.12, "defense": 0.98},
        {"name": "Mazatlan",               "attack": 1.08, "defense": 1.00},
        {"name": "FC Juarez",              "attack": 1.05, "defense": 1.03},
        {"name": "Queretaro",              "attack": 1.00, "defense": 1.06},
        {"name": "FC Juarez",              "attack": 0.96, "defense": 1.08},
    ],
    "BRA": [
        {"name": "Flamengo",               "attack": 1.90, "defense": 0.60},
        {"name": "Palmeiras",              "attack": 1.82, "defense": 0.62},
        {"name": "Atletico Mineiro",       "attack": 1.72, "defense": 0.66},
        {"name": "Fluminense",             "attack": 1.60, "defense": 0.70},
        {"name": "Corinthians",            "attack": 1.55, "defense": 0.72},
        {"name": "Gremio",                 "attack": 1.48, "defense": 0.75},
        {"name": "Internacional",          "attack": 1.45, "defense": 0.77},
        {"name": "Sao Paulo",              "attack": 1.40, "defense": 0.80},
        {"name": "Santos",                 "attack": 1.35, "defense": 0.83},
        {"name": "Botafogo",               "attack": 1.52, "defense": 0.73},
        {"name": "Vasco da Gama",          "attack": 1.25, "defense": 0.88},
        {"name": "Cruzeiro",               "attack": 1.30, "defense": 0.85},
        {"name": "Athletico Paranaense",   "attack": 1.38, "defense": 0.82},
        {"name": "Fortaleza",              "attack": 1.32, "defense": 0.84},
        {"name": "Bragantino",             "attack": 1.28, "defense": 0.87},
        {"name": "Goias",                  "attack": 1.15, "defense": 0.95},
        {"name": "Coritiba",               "attack": 1.10, "defense": 0.98},
        {"name": "Bahia",                  "attack": 1.20, "defense": 0.92},
        {"name": "America MG",             "attack": 1.05, "defense": 1.02},
        {"name": "Cuiaba",                 "attack": 0.98, "defense": 1.06},
    ],
    "ARG": [
        {"name": "River Plate",            "attack": 1.90, "defense": 0.60},
        {"name": "Boca Juniors",           "attack": 1.78, "defense": 0.63},
        {"name": "Racing Club",            "attack": 1.62, "defense": 0.68},
        {"name": "Independiente",          "attack": 1.52, "defense": 0.73},
        {"name": "San Lorenzo",            "attack": 1.48, "defense": 0.76},
        {"name": "Huracan",                "attack": 1.38, "defense": 0.82},
        {"name": "Estudiantes",            "attack": 1.42, "defense": 0.79},
        {"name": "Lanus",                  "attack": 1.35, "defense": 0.83},
        {"name": "Tigre",                  "attack": 1.28, "defense": 0.87},
        {"name": "Argentinos Juniors",     "attack": 1.32, "defense": 0.85},
        {"name": "Velez Sarsfield",        "attack": 1.30, "defense": 0.86},
        {"name": "Gimnasia LP",            "attack": 1.18, "defense": 0.93},
        {"name": "Colon",                  "attack": 1.15, "defense": 0.95},
        {"name": "Talleres",               "attack": 1.45, "defense": 0.77},
        {"name": "Defensa y Justicia",     "attack": 1.22, "defense": 0.91},
        {"name": "Platense",               "attack": 1.10, "defense": 0.98},
        {"name": "Banfield",               "attack": 1.12, "defense": 0.97},
        {"name": "Central Cordoba",        "attack": 1.05, "defense": 1.02},
        {"name": "Instituto",              "attack": 1.08, "defense": 1.00},
        {"name": "Godoy Cruz",             "attack": 1.20, "defense": 0.92},
    ],
    "WCQC": [
        {"name": "Argentina",              "attack": 2.10, "defense": 0.55},
        {"name": "Brasil",                 "attack": 2.05, "defense": 0.57},
        {"name": "Uruguay",                "attack": 1.72, "defense": 0.65},
        {"name": "Colombia",               "attack": 1.65, "defense": 0.68},
        {"name": "Ecuador",                "attack": 1.48, "defense": 0.75},
        {"name": "Chile",                  "attack": 1.42, "defense": 0.78},
        {"name": "Peru",                   "attack": 1.38, "defense": 0.80},
        {"name": "Paraguay",               "attack": 1.30, "defense": 0.85},
        {"name": "Venezuela",              "attack": 1.25, "defense": 0.88},
        {"name": "Bolivia",                "attack": 1.10, "defense": 0.96},
    ],
    "WCQU": [
        {"name": "Francia",                "attack": 2.05, "defense": 0.56},
        {"name": "España",                 "attack": 2.00, "defense": 0.57},
        {"name": "Inglaterra",             "attack": 1.92, "defense": 0.60},
        {"name": "Alemania",               "attack": 1.88, "defense": 0.62},
        {"name": "Portugal",               "attack": 1.85, "defense": 0.63},
        {"name": "Holanda",                "attack": 1.75, "defense": 0.66},
        {"name": "Belgica",                "attack": 1.68, "defense": 0.68},
        {"name": "Italia",                 "attack": 1.62, "defense": 0.70},
        {"name": "Croacia",                "attack": 1.48, "defense": 0.75},
        {"name": "Dinamarca",              "attack": 1.42, "defense": 0.78},
        {"name": "Suecia",                 "attack": 1.35, "defense": 0.83},
        {"name": "Suiza",                  "attack": 1.38, "defense": 0.81},
        {"name": "Austria",                "attack": 1.30, "defense": 0.86},
        {"name": "Polonia",                "attack": 1.28, "defense": 0.87},
        {"name": "Escocia",                "attack": 1.22, "defense": 0.91},
        {"name": "Turquia",                "attack": 1.25, "defense": 0.89},
    ],
    "SPL": [
        {"name": "Al-Hilal",               "attack": 1.95, "defense": 0.60},
        {"name": "Al-Nassr",               "attack": 1.88, "defense": 0.62},
        {"name": "Al-Ittihad",             "attack": 1.72, "defense": 0.67},
        {"name": "Al-Ahli",                "attack": 1.65, "defense": 0.70},
        {"name": "Al-Shabab",              "attack": 1.42, "defense": 0.79},
        {"name": "Al-Qadsiah",             "attack": 1.35, "defense": 0.83},
        {"name": "Al-Fayha",               "attack": 1.20, "defense": 0.92},
        {"name": "Al-Ettifaq",             "attack": 1.28, "defense": 0.87},
        {"name": "Al-Raed",                "attack": 1.15, "defense": 0.95},
        {"name": "Al-Taawoun",             "attack": 1.18, "defense": 0.93},
        {"name": "Al-Khaleej",             "attack": 1.10, "defense": 0.98},
        {"name": "Damac",                  "attack": 1.05, "defense": 1.02},
        {"name": "Al-Hazm",                "attack": 1.00, "defense": 1.05},
        {"name": "Al-Riyadh",              "attack": 0.96, "defense": 1.08},
        {"name": "Al-Okhdood",             "attack": 0.92, "defense": 1.10},
        {"name": "Al-Tai",                 "attack": 0.88, "defense": 1.14},
    ],
}


def _poisson_sample(lam: float) -> int:
    if lam <= 0:
        return 0
    L = math.exp(-lam)
    k, p = 0, 1.0
    while p > L:
        k += 1
        p *= random.random()
    return k - 1


def generate_finished_matches(league_code: str, n: int = 90, seed: int = 42) -> list[dict]:
    rng = random.Random(seed)
    teams = LEAGUE_TEAMS[league_code]
    matches = []
    team_list = teams.copy()
    rounds = (n // (len(team_list) // 2)) + 2
    for _ in range(rounds):
        rng.shuffle(team_list)
        for i in range(0, len(team_list) - 1, 2):
            if len(matches) >= n:
                break
            home = team_list[i]
            away = team_list[i + 1]
            lam_h = home["attack"] * away["defense"] * HOME_ADVANTAGE
            lam_a = away["attack"] * home["defense"]
            # Use rng for reproducibility
            random.seed(rng.randint(0, 999999))
            hg = _poisson_sample(lam_h)
            ag = _poisson_sample(lam_a)
            matches.append({
                "home_team": home["name"],
                "away_team": away["name"],
                "home_goals": hg,
                "away_goals": ag,
            })
    return matches[:n]


def generate_upcoming_fixtures(league_code: str, n: int = 12, seed: int = 99) -> list[dict]:
    rng = random.Random(seed)
    teams = LEAGUE_TEAMS[league_code].copy()
    rng.shuffle(teams)
    fixtures = []
    now = datetime.utcnow()
    day_offset = 2
    for i in range(0, len(teams) - 1, 2):
        if len(fixtures) >= n:
            break
        home = teams[i]
        away = teams[i + 1]
        fixtures.append({
            "id": abs(hash(f"{league_code}-{home['name']}-{away['name']}")),
            "date": (now + timedelta(days=day_offset)).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "status": "SCHEDULED",
            "home_team": home["name"],
            "away_team": away["name"],
            "home_goals": None,
            "away_goals": None,
            "league": league_code,
        })
        day_offset += 3
    return fixtures


def get_league_teams(league_code: str) -> list[str]:
    return [t["name"] for t in LEAGUE_TEAMS.get(league_code, [])]


def get_all_league_codes() -> list[str]:
    return list(LEAGUE_TEAMS.keys())
